services:
  mongo:
    container_name: mongo
    image: mongo:latest
    #environment:
    #- AUTH=yes
    #- MONGO_INITDB_ROOT_USERNAME=admin
    #- MONGO_INITDB_ROOT_PASSWORD=p@ssw0rd
    volumes:
      - ${MONGO_HOST_DATA}/db:/data/db
    ports:
      - "27017:27017"
  tokenapi:
    container_name: tokenapi
    build: .
    ports:
      - "8001:8001"
      - 5678:5678
    depends_on:
      - mongo
    env_file:
      - .env.docker
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn tokenapi.app.main:app --host 0.0.0.0 --port 8001 --reload"
      ]
